### ISSUE TITLE
compiling for windows

### ISSUE THREAD

**Issue by amircodota** [FillZpp/sys-info-rs#42]
Hi,

Trying to compile version 0.5.9 for x86_64-pc-windows-gnu fails.

error[E0425]: cannot find function `sysconf` in crate `libc`
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/sys-info-0.5.9/lib.rs:396:34
    |
396 |             let buf_size = libc::sysconf(libc::_SC_HOST_NAME_MAX) as usize;
    |                                  ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `_SC_HOST_NAME_MAX` in crate `libc`
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/sys-info-0.5.9/lib.rs:396:48
    |
396 |             let buf_size = libc::sysconf(libc::_SC_HOST_NAME_MAX) as usize;
    |                                                ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `gethostname` in crate `libc`
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/sys-info-0.5.9/lib.rs:398:22
    |
398 |             if libc::gethostname(buf.as_mut_ptr() as *mut i8, buf_size) < 0 {
    |                      ^^^^^^^^^^^ help: a function with a similar name exists: `getsockname`

error: aborting due to 3 previous errors

Version 0.5.8 works fine.

Amir

**Comment by bachue** [comment]
Got the same isssue, which has broken my ci test cases.
<img width="778" alt="Screen Shot 2020-02-13 at 12 22 12" src="https://user-images.githubusercontent.com/321962/74401195-7f1fc380-4e5b-11ea-9983-ce1a13b5b00c.png">

**Comment by gaoqiangz** [comment]
Got the same isssue

**Comment by SitiSchu** [comment]
This bug was introduced in v0.5.9 so as a temporary fix lock your `sys-info` crate to version `0.5.8` in your Cargo.toml:
```toml
[dependencies]
sys-info = "=0.5.8"
```

**Comment by Lonami** [comment]
Probably introduced in https://github.com/FillZpp/sys-info-rs/commit/558fb59e45434e65aa2d56a141ff4776641ded7f:

https://github.com/FillZpp/sys-info-rs/blob/ef69500f918d6eaee21287d807432bfdf0a06376/lib.rs#L393-L414

Since `cfg!()` is being used, the check is done at runtime, not compile time (which means it is compiled for Windows, which lacks this). The solution would be to use `#[cfg()]` on the function, to compile only the correct variant on the right operative system.

**Comment by WaffleLapkin** [comment]
There is also [`cfg-if`][cfgif] crate for such purposes.

[cfgif]: https://docs.rs/cfg-if

**Comment by SitiSchu** [comment]
@Lonami that was before v0.5.8 I think you meant ef69500f918d6eaee21287d807432bfdf0a06376 thats where the line with `libc::sysconf` was introduced

**Comment by Lonami** [comment]
Oh yeah, I probably copied the wrong link from `blame`. You can `blame` that mistake on me.
